#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xbindkeys &
/usr/bin/status_bar --config $HOME/.config/status_bar.lodpi.conf &
openbox &
