set-option -g status-keys vi
set-window-option -g mode-keys vi
set-option -g escape-time 0
bind-key C-b last-window
bind-key b send-prefix
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key < resize-pane -L 6
bind-key > resize-pane -R 6
bind-key - resize-pane -D 6
bind-key + resize-pane -U 6
bind-key s split-window -v
bind-key v split-window -h
bind-key y set-window-option synchronize-panes
bind-key t choose-session
bind-key Left previous-window
bind-key Right next-window
bind-key Escape copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi J send-keys -X cursor-down\; send-keys -X cursor-down\; send-keys -X cursor-down\; send-keys -X cursor-down\; send-keys -X cursor-down
bind-key -T copy-mode-vi K send-keys -X cursor-up\; send-keys -X cursor-up\; send-keys -X cursor-up\; send-keys -X cursor-up\; send-keys -X cursor-up
bind-key -T copy-mode-vi L send-keys -X cursor-right\; send-keys -X cursor-right\; send-keys -X cursor-right\; send-keys -X cursor-right\; send-keys -X cursor-right
bind-key -T copy-mode-vi H send-keys -X cursor-left\; send-keys -X cursor-left\; send-keys -X cursor-left\; send-keys -X cursor-left\; send-keys -X cursor-left
