require('paq-nvim'){
    'chadvoegele/nvim-slime';
    'neovim/nvim-lspconfig';
    'nvim-lua/completion-nvim';
    'nvim-lua/lsp-status.nvim';
    'nvim-lua/plenary.nvim';
    'nvim-lua/popup.nvim';
    'nvim-telescope/telescope.nvim';
    'nvim-treesitter/nvim-treesitter';
    'savq/paq-nvim';
}
